//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sql___trener
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompleteTask
    {
        public int ID { get; set; }
        public string User { get; set; }
        public int Task { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual User User1 { get; set; }
        public virtual Task Task1 { get; set; }
    }
}
