//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sql___trener
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.CompleteTasks = new HashSet<CompleteTask>();
        }
    
        public int TaskId { get; set; }
        public int Skills { get; set; }
        public int Difficult { get; set; }
        public string TaskName { get; set; }
        public string Info { get; set; }
        public string RightAnswer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompleteTask> CompleteTasks { get; set; }
        public virtual Difficulty Difficulty { get; set; }
        public virtual Skill Skill { get; set; }

        public override string ToString()
        {
            return TaskName + ": " + Skill.SkillName + ", " + Difficulty.DifName;
        }
    }
}
